set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

find_package(PkgConfig REQUIRED)
pkg_check_modules(VORTEX_FFTW3 REQUIRED fftw3)
pkg_check_modules(VORTEX_FFTW3F REQUIRED fftw3f)

set(VORTEX_CORE_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/dynamics.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/environment.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/simulation.cpp
  PARENT_SCOPE
)

set(VORTEX_CORE_INCLUDE_DIRS
  ${CMAKE_CURRENT_SOURCE_DIR}
  ${CMAKE_SOURCE_DIR}/_deps/eigen
  ${VORTEX_FFTW3_INCLUDE_DIRS}
  ${VORTEX_FFTW3F_INCLUDE_DIRS}
  PARENT_SCOPE
)

set(VORTEX_CORE_LINK_LIBRARIES
  ${VORTEX_FFTW3_LIBRARIES}
  ${VORTEX_FFTW3F_LIBRARIES}
  PARENT_SCOPE
)
